name: Python Tests

on:
  pull_request:
    branches:
      - main  # or any other branches you want to trigger the tests on

jobs:
  test:

    runs-on: windows-latest

    strategy:
      matrix:
        python-version: [3.9]  # Specify the Python versions to test against

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to the latest version

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4  # Updated to the latest version
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if (Test-Path requirements.txt) { pip install -r requirements.txt }

    - name: Run tests
      run: |
        pytest
