name: Python Tests

on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["windows-latest"]
        python-version: ["3.9"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies and pytest
        run: |
          pip install -e .
          pip install -r requirements.txt

      - name: Set Python Path
        run: |
          # export PYTHONPATH="${PYTHONPATH}:$(pwd)"  # Linux/macOS
          # For Windows, use the following line instead:
          $env:PYTHONPATH += ";${env:GITHUB_WORKSPACE}"

      - name: Run tests
        run: pytest
